(ns game.script
  (:use-macros [novelette.syntax :only [defspeaker defscene defblock narrate default
                                        clear-sprites sprite no-sprite teleport-sprite
                                        bgm no-bgm declare-sprite clear-backgrounds background
                                        no-background show-ui hide-ui set-ui set-cursor set-cps
                                        set-bounds set-nametag-position wait jump-to-scene]])
  (:use [novelette.syntax :only [option choice]]))

(defspeaker alex "Alex" :white)
(defspeaker elisa "Elisa" :brown)
(defspeaker kurt "Kurt" :yellow)
(defspeaker angel "AngelBlue" :cyan)
(defspeaker mom "Mom" :lightcoral)
(defspeaker elisangel "Elisa & Angel" :pink)
(defspeaker irc "IRC" :grey)
(defspeaker pc "PC" :paleturquoise)

(def kurt-coords [950 150])
(def elisa-coords [950 170])
(def angel-coords [950 210])

(defblock reset-sprites
  (teleport-sprite :kurt-angry kurt-coords)
  (teleport-sprite :kurt-happy kurt-coords)
  (teleport-sprite :kurt-fire kurt-coords)
  (teleport-sprite :elisa-angry elisa-coords)
  (teleport-sprite :elisa-happy elisa-coords)
  (teleport-sprite :elisa-blush elisa-coords)
  (teleport-sprite :angelblue-normal angel-coords)
  (teleport-sprite :angelblue-angry angel-coords)
  (teleport-sprite :angelblue-crazy angel-coords))

(defblock move-group-sprite
  (teleport-sprite :kurt-angry   (update-in kurt-coords [0] - 900))
  (teleport-sprite :kurt-happy   (update-in kurt-coords [0] - 900))
  (teleport-sprite :kurt-fire    (update-in kurt-coords [0] - 900))
  (teleport-sprite :angelblue-normal (update-in angel-coords [0] - 450))
  (teleport-sprite :angelblue-angry  (update-in angel-coords [0] - 450))
  (teleport-sprite :angelblue-crazy  (update-in angel-coords [0] - 450)))

(defblock normal-text
  (set-nametag-position [55 490])
  (set-bounds 40 540 (- 1280 80) (- 800 540)))

(defblock narrator-text
  (set-bounds 260 300 (- 1280 700) (- 800 540)))

(defblock init
  (set-cps 30)
  (set-ui :dialogue-ui [0 420]) ; blaze it
  (normal-text)
  (declare-sprite :kurt-angry :kurt-angry kurt-coords 2)
  (declare-sprite :kurt-happy :kurt-happy kurt-coords 2)
  (declare-sprite :kurt-fire :kurt-fire kurt-coords 2)
  (declare-sprite :angelblue-normal :angelblue-normal angel-coords 3)
  (declare-sprite :angelblue-crazy :angelblue-crazy angel-coords 3)
  (declare-sprite :angelblue-angry :angelblue-angry angel-coords 3)
  (declare-sprite :elisa-angry :elisa-angry elisa-coords 1)
  (declare-sprite :elisa-happy :elisa-happy elisa-coords 1)
  (declare-sprite :elisa-blush :elisa-blush elisa-coords 1))

(defblock sleep-day-2
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "The night is full of dreams about games, deadlines and heated IRC arguments.")
  (normal-text)
  (background :background)
  (show-ui))

(defscene thanks-for-playing
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "THE END.")
  (narrate "Thanks for playing!"))

(defscene day-3-end-angel
  (show-ui)
  (bgm :main-theme)
  (move-group-sprite)
  (sprite :kurt-fire)
  (sprite :elisa-happy)
  (sprite :angelblue-normal)
  (kurt "Go! Alex come on, upload faster!")
  (alex "I can't, man, this game is massive. Give it some time!")
  (narrate "The upload bar still shows 10 minutes left, there are not that many before the end of the deadline either.")
  (no-sprite :angelblue-normal)
  (sprite :angelblue-crazy)
  (angel "If this fails to upload, I'm going to strangle somebody...")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-normal)
  (alex "Don't look at me.")
  (elisa "Come on guys... aren't you happy we managed to finish this in time?")
  (alex "Honestly? I would've never expected that. There are still a lot of issues I need to work on. Luckily they let you fix bugs after the deadline.")
  (kurt "Yeah, this game is seriously awesome.")
  (angel "A masterwork of mechanics and balancing, ahem.")
  (kurt "True, Angel. I'm sorry I doubted you. It does really play well and the theme is not far off either.")
  (alex "Definitely not off, it's very original compared to most of the games I've seen around.")
  (elisa "Yeah, and it looks so cute too.")
  (angel "That's thanks to your art!")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "Heh, t-thanks.")
  (no-sprite :elisa-blush)
  (sprite :elisa-happy)
  (narrate "The game finishes uploading as the clock strikes exactly 5 minutes before the deadline. The website feels very sluggish as thousands of people try to submit their product in unison.")
  (alex "It's done! This timing is really crazy guys, we got really close to missing the deadline. Never again.")
  (angel "I agree...")
  (kurt "Look who's talking... Hey dude, weren't you the one arguing for a bigger and more complex game?")
  (no-sprite :angelblue-normal)
  (sprite :angelblue-crazy)
  (angel "Shut up, you! And, by the way, I'm not a dude...")
  (alex "Uh? What do you mean?")
  (elisa "Angel is a girl, guys...")
  (narrate "“Ah... WHAT?!”")
  (kurt "You're shitting me...")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-angry)
  (angel "Rude...")
  (alex "Really?!")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "You never noticed? Just look at her nick! It's so obvious...")
  (angel "Yeah, it is... Really guys, what is wrong with you?")
  (narrate "“It does make sense...”")
  (no-sprite :kurt-fire)
  (sprite :kurt-happy)
  (kurt "Okay, let's forget this... We should probably get some rest now. We could meet up during next week for a coffee someplace, what do you guys think?")
  (no-sprite :angelblue-angry)
  (sprite :angelblue-crazy)
  (angel "Irl? Do you want to hit on me or something?")
  (kurt "What? No, of course not! It's just to hang out and relax after all this stressful work.")
  (alex "Sure, why not?")
  (elisa "Can I join too?")
  (kurt "Of course! We also have to plan for our next game! This time I'm aiming for something smaller, though.")
  (alex "Oh you guys...")
  (clear-sprites)
  (narrate "As we keep talking to each other, we make arrangements and plans for future games to work on. Everyone is feeling very burnt out though, all the ideas are much simpler.")
  (narrate "“It looks like I got stuck with this...”")
  (narrate "“It ain't so bad, after all...”")
  (jump-to-scene thanks-for-playing))

(defscene day-3-end-elisa
  (show-ui)
  (bgm :main-theme)
  (move-group-sprite)
  (sprite :kurt-fire)
  (sprite :elisa-happy)
  (sprite :angelblue-normal)
  (kurt "It's done!")
  (angel "Well, that was certainly something...")
  (narrate "I give a sigh of relief as I click the 'submit' button on the Ludum Dare website. There's still plenty of time left, but we have reached a state where we are all content of our game.")
  (elisa "We can still fix bugs after submission, right?")
  (alex "Yes, and we still have some hours left in case we want to expand on it a bit more.")
  (angel "Nah, the game is good as is. Expanding it would just make it bloated and harder to balance.")
  (narrate "The change of stance in Angel regarding game complexity is remarkable and it makes me smirk in amusement.")
  (kurt "Look who's talking... Hey dude, weren't you the one arguing for a bigger and more complex game?")
  (no-sprite :angelblue-normal)
  (sprite :angelblue-crazy)
  (angel "Shut up, you! And, by the way, I'm not a dude...")
  (alex "Uh? What do you mean?")
  (elisa "Angel is a girl, guys...")
  (narrate "“Ah... WHAT?!”")
  (kurt "You're shitting me...")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-angry)
  (angel "Rude...")
  (alex "Really?!")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "You never noticed? Just look at her nick! It's so obvious...")
  (angel "Yeah, it is... Really guys, what is wrong with you?")
  (narrate "“It does make sense...”")
  (no-sprite :kurt-fire)
  (sprite :kurt-happy)
  (kurt "Okay, let's forget this... We still have plenty of time before the weekend ends, what do you guys think? Wanna meet up somewhere and go get something to eat together?")
  (no-sprite :angelblue-angry)
  (sprite :angelblue-crazy)
  (angel "Irl? Do you want to hit on me or something?")
  (kurt "What? No, of course not! It's just to hang out and relax after all this stressful work.")
  (alex "Sure, why not?")
  (elisa "Can I join too?")
  (kurt "Of course! We also have to plan for our next game! This time I want to make it big!")
  (alex "Oh you guys...")
  (clear-sprites)
  (narrate "As we keep talking to each other, we make arrangements to meet over the course of the following week as well.")
  (narrate "“It looks like I got stuck with this...”")
  (narrate "“It ain't so bad, after all...”")
  (jump-to-scene thanks-for-playing))

(defscene day-3-elisa
  (show-ui)
  (bgm :day3-nice)
  (narrate "After a full night of sleep, the alarm graciously wakes me.")
  (narrate "I feel rested and reinvigorated, I am looking forward to showing my progress to the others. The game is getting closer to being finished soon")
  (narrate "Skipping breakfast, I decide to jump straight onto IRC.")
  (background :irc)
  (narrate "Angel is already in the channel, the others are nowhere to be seen.")
  (alex "Yo, morning.")
  (sprite :angelblue-normal)
  (angel "Hey, cowboy. How's the development going?")
  (narrate "“Straight to the point, great.”")
  (alex "The prototype's finished. The engine is ready to be used as soon as we have art and music.")
  (angel "Nice! Can I try it? What else is there to do?")
  (alex "I need to fix a couple of bugs and typos and add some polishing around the corners, but not much else on my side, I guess.")
  (alex "Hang on, let me send you a copy.")
  (clear-sprites)
  (move-group-sprite)
  (narrate "I tab out of the client and fire up our shared hosting application.")
  (narrate "A couple of minutes later it completes the upload and I copypaste the link in the chat.")
  (sprite :kurt-happy)
  (kurt "What's this?")
  (sprite :elisa-happy)
  (elisa "Morning, Alex")
  (narrate "While I wasn't looking, the others had joined us in the channel.")
  (sprite :angelblue-crazy)
  (angel "It's our road to success, you dumb!")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-normal)
  (alex "It's the engine. It's mostly completed. Minus a few bugs but we can work around those. Feel free to give it a try.")
  (no-sprite :kurt-happy)
  (sprite :kurt-fire)
  (kurt "Seriously?! Wow, you're amazing, man! I'm trying this right now!")
  (narrate "I smile by myself, it wasn't that complicated, Elisa's game idea was fairly simple.")
  (no-sprite :kurt-fire)
  (narrate "Suddenly, Kurt logs out, probably off to try the game.")
  (alex "How's the art coming, Elisa?")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "I've got a few models finished, there's still a lot of room for improvement and a lot of stuff to work on, but I'm satisfied with this.")
  (angel "Oh? Really? Nice, can we see some examples?")
  (narrate "Elisa posts a couple of Noartdev links. I open one and I am immediately awestruck by the choices of colors and composition.")
  (alex "You made this?!")
  (elisa "Yes...")
  (alex "It's amazing! This is really awesome, you should do this professionally. You definitely have the skills.")
  (elisa "Heh, thanks. It's nothing, really.")
  (no-sprite :angelblue-normal)
  (sprite :angelblue-crazy)
  (angel "No, he's right! This stuff is really good!")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-normal)
  (angel "There are a couple of changes I would make, though. Like here...")
  (clear-sprites)
  (narrate "I tab out of the client and head to the Ludum Dare website to get updated with the state of the competition.")
  (no-background)
  (narrate "There are several posts of developers dropping out due to stress, finishing early because of burn out and just the usual posting of updates.")
  (narrate "Some games look very nice, some others not so much. In each of them, however, you can see the effort that was put into every detail by the developer.")
  (narrate "“This one is not so bad...”")
  (narrate "I click on a few more, I try to compare our level of art with theirs. There are definitely games illustrated by professional designers, it is very hard to compete at our level.")
  (pc "BEEP")
  (narrate "Somebody has mentioned my name on IRC. I tab back into the client. It appears Kurt is back as well.")
  (background :irc)
  (sprite :kurt-happy)
  (sprite :elisa-happy)
  (sprite :angelblue-normal)
  (kurt "Yo, Alex, this engine is really something! We can get something awesome going on in here.")
  (alex "Heh, thanks man. I appreciate it.")
  (kurt "Alright, so this is our current state. We are on track as planned. I am almost done composing the music, I just need some extra time with mastering.")
  (angel "I'll need to work out some of the formulas for the engine as there are some changes I would like to make.")
  (alex "Sure, let me know what and I will help.")
  (angel "Thanks. Elisa, can we talk about a few enemies I would like to introduce in the game?")
  (elisa "Sure thing, Psyke?")
  (angel "Yeah, it's easier this way.")
  (no-sprite :elisa-happy)
  (no-sprite :angelblue-normal)
  (narrate "The two of them disconnect from the channel.")
  (clear-sprites)
  (reset-sprites)
  (sprite :kurt-fire)
  (kurt "This is so good, I'm totally hyped! I'm going back to work on the music now. Catch with you later, Alex!")
  (no-sprite :kurt-fire)
  (no-background)
  (narrate "I am left alone online and I decide to tab into Derrit for some minutes, to catch up with the latest news and posts of cats.")
  (narrate "Outside of the window snow is gently falling from the sky, slowly amassing on our porch. Children are yet again outside playing in the snow.")
  (narrate "“Time for the last rush to the deadline!”")
  (narrate "I try to motivate myself as I jump back into bugfixing and gameplay smoothing. Occasionally I get interrupted by Kurt or Angel, asking for status updates. Elisa is much more reserved and completely immersed in her work, I barely hear from her.")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "Some hours of intense work later...")
  (normal-text)
  (background :background)
  (show-ui)
  (jump-to-scene day-3-end-elisa))

(defscene day-3-angel
  (show-ui)
  (bgm :day3-bad)
  (narrate "After a troubled night with little sleep, the alarm yanks me out of my tormented dream.")
  (narrate "I feel very bad, my stomach is all jumbled and I am definitely not looking forward to showing my lack of progress to the others. I see a long road ahead before we can call this finished.")
  (narrate "Skipping breakfast, I decide to jump straight onto IRC.")
  (background :irc)
  (narrate "Angel is already in the channel, the others are nowhere to be seen.")
  (alex "Hi.")
  (sprite :angelblue-normal)
  (angel "Hey Alex, how's progress?")
  (narrate "“Straight to the point, damn.”")
  (alex "Heh... It's going slowly. The engine is technically feature-complete, but there are issues and bugs everywhere. If you can get it to run without crashes, it might work.")
  (narrate "“Might...”")
  (alex "Yesterday I made it crash by just flipping two items in the inventory... There is so much state everywhere, it is so hard to keep everything in place.")
  (angel "Don't worry too much, we still have time.")
  (move-group-sprite)
  (sprite :kurt-happy)
  (sprite :elisa-angry)
  (kurt "Hey!")
  (elisa "Good morning...")
  (narrate "As everyone has joined the channel, we promptly start to talk about the plans for the day.")
  (kurt "Guys, I would love to stay, but I have to finish to record all these tracks and the amount of work is killing me.")
  (angel "Don't worry, wimp, just let us know when the music's done. We'll work on the rest without you.")
  (alex "Yeah, it's all good, man. Catch you later!")
  (no-sprite :kurt-happy)
  (elisa "How's everyone else doing?")
  (alex "Badly.")
  (angel "Not so great either, there are some balancing issues I hadn't considered...")
  (elisa "I have a lot to work on, too. Shall we keep in touch today?")
  (alex "Yes, but I'll have to log out. I need to focus and I'm a rush at the moment. There's so much I still need to fix. You can send me a text or an email if you need, though.")
  (angel "Same... Maybe this wasn't a good idea...")
  (alex "It's too early to say, Angel. Cheer up, we can do it.")
  (narrate "“I hope.”")
  (angel "Thanks, I appreciate that.")
  (alex "Alright guys, I'm going as well now. Good luck to you both. Talk to you later!")
  (elisa "Bye.")
  (angel "Cya")
  (no-background)
  (clear-sprites)
  (narrate "I log out of the client and stare at the pile of notes and files with TODO comments everywhere.")
  (narrate "Outside there is a massive storm, even this early in the morning. It might have been the cause of my troubled dreams. That, or the upcoming deadline. Most likely the latter.")
  (narrate "“Time for the last painful rush, then!”")
  (narrate "I try to motivate myself, hardly, as I jump back into bugfixing and issue juggling. Occasionally I get interrupted by Kurt or Angel, crying for help with some new issue they discovered in our plans. Elisa is much more reserved and completely immersed in her work, I barely hear from her.")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "Many hours of very intense work later...")
  (normal-text)
  (background :background)
  (show-ui)
  (jump-to-scene day-3-end-angel))

(defscene elisa-chosen
  (show-ui)
  (background :irc)
  (narrate "Everyone is here, Alex and Angel seem to be in the middle of a conversation about sound and gameplay interaction.")
  (clear-sprites)
  (sprite :angelblue-normal)
  (sprite :elisa-happy)
  (sprite :kurt-happy)
  (kurt "Sound is fundamental to get the proper feeling of immersion in a game.")
  (angel "Yes, but you need fluid mechanics and balanced gameplay too.")
  (elisa "And decent artwork too, otherwise it will look ugly!")
  (kurt "Oh, here he is, welcome back Alex. Ready to kick asses?")
  (narrate "I smile at Kurt's statement. It's just game development after all.")
  (alex "You bet.")
  (narrate "“It's fun with friends, though. Not that I would ever admit that.”")
  (kurt "Okay guys, we're all here. We have wasted enough time so it's better to get to work.")
  (angel "Yes, time is running short, even though the game is simple enough we want to make sure we have enough testing done before the deadline.")
  (alex "Just let me have carte blanche on the game code and I'm ready to start.")
  (kurt "You have it. Angel, what music do you think would fit best with this type of game?")
  (narrate "My thoughts drift to various implementation details I will have to consider to write the game, my mind is already wandering away from the conversation on IRC.")
  (angel "...arcade-like... ...chiptune... ...pixel art...")
  (elisa "...couple of hours. Three maybe. What about you Alex?")
  (narrate "The client window pings me as my name gets mentioned. I quickly read up the logs to get back on topic. They were talking about deadlines.")
  (alex "I should have a proper prototype in around 6 hours. Before tomorrow morning the engine should be ready and then we can playtest it and smooth out issues.")
  (kurt "That's great! Let's start then.")
  (alex "I'll log off IRC, it's too distracting. Send me a mail or text if you need me, alright?")
  (kurt "Got it, godspeed!")
  (clear-sprites)
  (no-background)
  (narrate "I close the program and go grab a glass of water in order to clear my thoughts. It's going to be a long weekend...")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "8 hours later...")
  (normal-text)
  (background :background) ; DARK LAYER BACKGROUND + FOOD
  (show-ui)
  (narrate "“And it's done! It should be playable now.”")
  (narrate "I spent the last eight hours working without pause on the engine. There were bugs and issues, it was not easy to get used to the different type of logic in games compared to normal applications, however it is ready now.")
  (narrate "I give it another spin with some placeholder art and it seems to be running well. The clock is about to strike midnight and I realize my room has gotten darker around me.")
  (narrate "“I should head to bed, I'll let the others know tomorrow morning. I can't wait!”")
  (sleep-day-2)
  (jump-to-scene day-3-elisa))

(defscene angel-chosen
  (show-ui)
  (alex "Alright, if we really want to do this, we need to put all of our effort into it.")
  (alex "This game won't be easy to make, it is a very ambitious project and we'll also need to justify the theme adaptation somehow.")
  (angel "Let me deal with that, we'll be the most original ones, trust me.")
  (kurt "I count on that, Angel. I'll make the best score a game has ever had.")
  (elisa "I'll work hard on the character effects, we'll have the best looking game out there, I promise you.")
  (narrate "Everyone seems to be very excited and hyped at this ambitious idea.")
  (narrate "“Maybe it wasn't a bad choice, in retrospective.”")
  (alex "Awesome guys, let's get to work. I'll need to log out and cut off all distractions to properly work on this. Let me know with a mail or text if you need me, alright?")
  (angel "Definitely, do your best, man. Do you have an estimate on when we'll be able to have a testable prototype?")
  (narrate "I take my time to thoroughly think about the design. My mind wanders to various design choices and implementation details.")
  (narrate "“Definitely not easy.”")
  (alex "I hope I can get it to a working state before midnight, but I can't promise anything. You guys work on the rest, I will adapt to it.")
  (kurt "We can't do much more anyhow. Godspeed Alex")
  (no-background)
  (clear-sprites)
  (narrate "I close the program and go grab a glass of water in order to clear my thoughts. It's going to be a very long weekend...")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "15 hours later...")
  (normal-text)
  (background :background) ; DARK LAYER BACKGROUND + FOOD
  (show-ui)
  (narrate "“Well, at least something's moving on the screen at the moment.”")
  (narrate "I spent the whole day working without pause on the engine. There are still a lot of bugs and issues, however it is more or less playable now.")
  (narrate "I give it another spin with some placeholder art and it crashes after a few minutes of playing.")
  (narrate "“Awesome, another bug...”")
  (narrate "The clock is about to strike midnight and I realize my room has gotten darker around me.")
  (narrate "“I should head to bed, I'll fix this tomorrow, first thing I'll do in the morning.”")
  (sleep-day-2)
  (jump-to-scene day-3-angel))

(defscene other-chosen
  (show-ui)
  (alex "kek"))

(defscene elisa-bridge
  (show-ui)
  (alex "Realistically speaking, Elisa's idea is the most fitting, we should really go with hers.")
  (kurt "I agree, it's a wise choice. It's better not to try anything risky the first time.")
  (angel "Pfft! Do whatever you want, nerds.")
  (clear-sprites)
  (sprite :angelblue-normal)
  (sprite :elisa-happy)
  (sprite :kurt-happy)
  (elisa "Thanks Alex, I appreciate it.")
  (alex "There is one condition though...")
  (narrate "I was deeply bothered by everybody constantly relying on me. Especially in a situation like this one where I have no prior experience whatsoever.")
  (alex "...I won't be the leader. Just let me do my own thing. If you want somebody to blame or look up to, go with Kurt. He dragged us all into this after all.")
  (elisangel "Ok.")
  (kurt "What? Really? I can be in charge?")
  (alex "Sure, pal. I don't play well when pressured with responsibilities. Give me something to do and I'll do it. Don't ask me to lead though.")
  (no-sprite :kurt-happy)
  (sprite :kurt-fire)
  (kurt "Whoo! Thank you! Alright minions! It's time to rock!")
  (narrate "“He seems so psyched, I hope I made a good choice.”")
  (kurt "First of all, it's getting late. We should probably have a lunch break.")
  (narrate "The clock is about to hit 12:00pm, my mother will be home soon for lunch.")
  (alex "It's a good idea. We can think this over alone and meet again here in a couple of hours, what do you guys think?")
  (elisangel "Ok.")
  (kurt "Hey, I thought I was the boss now... and yes, let's meet here in a few.")
  (clear-sprites)
  (narrate "One by one, the others log off the network. I decide to go read up on Derrit and game development a bit more.")
  (narrate "An abundant half-hour is over before my mother comes home.")
  (mom "Lunch's ready!")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "I leave my PC and head downstairs for lunch with my family.")
  (normal-text)
  (background :background)
  (show-ui)
  (narrate "After lunch is over, I head back to my room and log onto IRC.")
  (background :irc)
  (jump-to-scene elisa-chosen))

(defscene elisa-bridge-extra
  (show-ui)
  (alex "Alright, I'm in.")
  (no-sprite :elisa-blush)
  (sprite :elisa-happy)
  (narrate "She looks very happy, as if someone had taken a big weight off her chest.")
  (elisa "Thank you!")
  (alex "But... please don't make me in charge of everything. Just let me work and do my thing, you guys take care of everything else")
  (narrate "“All I want is to just code, why can't they understand it?”")
  (elisa "Yes, we already decided that Kurt will be the one in charge.")
  (narrate "She lets out a small laugh while looking at a screen. She's obviously looking at another window while talking to me.")
  (alex "Still on IRC?")
  (elisa "Yup, the others are celebrating your comeback.")
  (alex "You're really liking the thing, aren't you?")
  (elisa "It's useful to keep in touch, it's surprisingly simple.")
  (alex "Alright, let me relog in. I'll see you there in a few.")
  (elisa "Bye!")
  (no-sprite :elisa-happy)
  (move-group-sprite)
  (narrate "Waving my goodbye, I disconnect from Psyke and head back to IRC.")
  (no-background)
  (bgm :main-theme)
  (jump-to-scene elisa-chosen))

(defscene angel-bridge
  (show-ui)
  (alex "Where's the fun in doing something easy? Let's try something more adventurous.")
  (narrate "“I know I'm digging my own grave here.”")
  (alex "I choose Angel's game idea, it sounds more intriguing and interesting to work on. Sorry Elisa.")
  (clear-sprites)
  (sprite :angelblue-crazy)
  (sprite :elisa-happy)
  (sprite :kurt-happy)
  (elisa "It's... It's ok.")
  (angel "Aww yeah, bitches! It's happening!")
  (narrate "“I will never like this guy, did I make the wrong choice?”")
  (kurt "It's good to me too, but please tone it down a notch, Angel.")
  (angel "Are you mad because I won? Uh?")
  (narrate "I decide it's better to take control of the situation, before it gets out of hand.")
  (alex "Alright buddy, we get it. Let's think about what we'll be working on. We need to divide roles with each other.")
  (kurt "Good idea. I will probably take care of the music as that's the only thing I'm good at.")
  (elisa "You guys called me for art, right? Well, here I am.")
  (angel "I'm doing game design and balancing of mechanics.")
  (alex "And I'm programming. Great.")
  (jump-to-scene angel-chosen))

(defscene none-chosen
  (show-ui)
  (bgm :day2-sad)
  (narrate "I try to evaluate all my options. I don't really want to be in charge of this. Kurt is the one that dragged me into it in the first place.")
  (narrate "“I have never even made a game before, how am I supposed to choose?”")
  (alex "Alright, here's the deal.")
  (narrate "The chat is completely silent, everyone is waiting for my verdict.")
  (alex "I'm out.")
  (narrate "Thinking about the things I read from the night before, I recognize how fun making game can be. However I also realize how complex it is.")
  (alex "This stuff is really out of my league, you guys keep arguing, I don't want to be the 'boss'. I just wanted to have a relaxing weekend.")
  (kurt "What? Come on man, we haven't even started yet!")
  (angel "What a loser...")
  (narrate "I feel bad for letting Kurt down, but I really cannot work with these people. I'm not a gret team player either.")
  (alex "You are probably better off without me, guys.")
  (narrate "Voices are coming in my room from my window, there are kids playing outside in the snow, again.")
  (narrate "It's already almost lunch time and I have been wasting my weekend morning on this nonsense.")
  (elisa "So you're really out, Alex?")
  (clear-sprites)
  (narrate "I glance back at the screen, I don't really feel like answering, so I just turn it off and lean back on my chair.")
  (no-background)
  (narrate "“Ahh... screw this, I'll go watch some TV.”")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "A few hours pass before I decide to head back to my room.")
  (normal-text)
  (reset-sprites)
  (background :background) ; BACKGROUND ADD BREAKFAST??
  (show-ui)
  (narrate "My empty breakfast bowl is still on the desk so I decide to put it away.")
  (pc "BEEP. BEEP. BEEP.")
  (background :psyke)
  (narrate "The computer plays a melody, somebody is calling me on Psyke"); REMOVE BREAKFAST??
  (narrate "“I thought I had closed this crap...”")
  (narrate "It's Elisa. I put on my headset and take the call.")
  (alex "Hey")
  (sprite :elisa-happy)
  (elisa "Hey Alex. How are you? I'm sorry about what happened earlier...")
  (narrate "She is putting up a compassionate smile. She seems genuinely ashamed of what happened this morning.")
  (alex "It's not your fault Elisa, don't worry. You guys all feel very strongly about this, I just cannot fit in.")
  (alex "Seeing you talk about this, I realize that it's better if you just let me out of it.")
  (elisa "Well, in the end we decided to let Kurt choose. He was the calmest one in the group, after all.")
  (narrate "“A wise choice, for once.”")
  (narrate "Elisa is staring at her screen, straight at me, as if expecting something.")
  (alex "What? Oh...")
  (narrate "I realize a split second too late, she wants me to ask her who won.")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "N-nothing...")
  (alex "Well? Which game did you guys choose then?")
  (elisa "Mine.")
  (no-sprite :elisa-blush)
  (sprite :elisa-happy)
  (narrate "She smiles, she looks really happy about it.")
  (alex "I'm glad, it seems like a viable game to make. Good luck!")
  (narrate "As my cursor is about to click the 'interrupt call' button, she stutters.")
  (elisa "W-w-wait... There is a problem.")
  (narrate "“Why do I know these are not good news for me?”")
  (alex "Yes?")
  (elisa "We really need a programmer. None of us knows how to even start.")
  (alex "And let me guess, you thought of me, right?")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "If possible...")
  (narrate "She blushes, evidently embarrassed.")
  (narrate "“Looks like I cannot escape this.”")
  ;(hide-ui)
  (jump-to-scene elisa-bridge-extra))
  ;(choice
  ; "Will you help them?"
  ; (option "Yes." elisa-bridge-extra)
  ; (option "Yes, but..." other-chosen)
  ; (default "Yes.")))

(defscene morning-meeting-pt2
  (show-ui)
  (narrate "For once I find myself agreeing with Kurt. He seems to be taking this competition very seriously, I wouldn't want to let him down. I hadn't seen him this focused in a while.")
  (alex "I agree with all of you. The theme is weird, but it's also what we have.")
  (alex "Now, what did you guys have in mind?")
  (elisangel "Okay, my idea is the following:")
  (alex "Hold it!")
  (narrate "I quickly interject, before both start sending walls of text and spam the whole channel.")
  (alex "Go one at a time. Elisa, yes?")
  (no-sprite :elisa-angry)
  (no-sprite :kurt-angry)
  (sprite :kurt-happy)
  (sprite :elisa-blush)
  (elisa "Well...")
  (narrate "Everyone in the chat waits for her. She doesn't seem to be used to chat clients and she takes her time to properly convey her point across.")
  (elisa "The theme says to only use one screen, right? Well...")
  (angel "No it doesn't.")
  (kurt "Blue, wait for your turn.")
  (elisa "mmm... yeah, the thing is this. I was thinking we could have a small arcade game, like a mix of pac-man and tetris, where you move around a maze which is constantly changing.")
  (elisa "The player can move around and can also modify the layout of the maze based on various combinations of actions and bonuses.")
  (narrate "Then she adds, after a few seconds of silence, almost as an afterthought.")
  (elisa "And of course there are enemies trying to get you!")
  (angel "That's so stupid. It's not original, it's just plain boring!")
  (narrate "I almost snap at Angel, I am getting really annoyed by his aggressive tone.")
  (alex "Listen buddy, try to be more productive. I'd raher hear your idea now instead of your complaints.")
  (no-sprite :angelblue-angry)
  (sprite :angelblue-crazy)
  (angel "A'ight boss, here goes.")
  (narrate "“Who made me the boss of this farce?”")
  (angel "My game is an RPG. Like Ultimate Fiction, you know?")
  (narrate "Ultimate Fiction is a famous turn-based japanese RPG game for consoles.")
  (alex "Yes...?")
  (angel "Well, it has turn-based combat. You go and explore dungeons, except here's the catch: the characters are just actors of a play.")
  (angel "It is just like a theatre or movie show. You see the game through a TV monitor and the more audience you can get, the stronger your party becomes.")
  (kurt "That's not really on a screen, though... It breaks the theme.")
  (angel "Yes it is! It's on a TV screen!")
  (elisa "Isn't that... cheating?")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-angry)
  (angel "No! How HARD is it to understand. A theme is a T-H-E-M-E, not a RULE.")
  (no-sprite :elisa-blush)
  (sprite :elisa-angry)
  (no-sprite :kurt-happy)
  (sprite :kurt-angry)
  (kurt "Yo, down with the capslock, buddy.")
  (angel "Why don't you guys get it?")
  (narrate "I glance over the rules of the competition looking for something that could help us solve this impasse.")
  (alex "Well... here the site does mention the theme not being strict. It seems we'll be rated on the theme as well though...")
  (alex "As long as we can properly justify it, I think it shouldn't be a problem.")
  (no-sprite :angelblue-crazy)
  (sprite :angelblue-angry)
  (angel "Ha!")
  (alex "But! Your idea really sounds very complex. I doubt we'd be able to pull this off in two days, and the clock is already ticking.")
  (alex "At the same time, Elisa's option is very simple.")
  (narrate "According to my wild guesses, it shouldn't take more than a day to get it working code-wise.")
  (alex "We also need to rely on art and music so we need to keep that in mind. How much art do you need to keep such a simple game also interesting?")
  (no-sprite :elisa-angry)
  (sprite :elisa-happy)
  (elisa "I'll work on the art, I already have some ideas about it.")
  (no-sprite :kurt-angry)
  (sprite :kurt-happy)
  (kurt "So, what will it be then, boss?")
  (narrate "I stare at my name highlighted next to 'boss'.")
  (alex "Are you talking to me?")
  (kurt "Of course! I'd say you pick a choice and we'll work around that. What do you guys say?")
  (no-sprite :angelblue-angry)
  (sprite :angelblue-normal)
  (no-sprite :elisa-angry)
  (sprite :elisa-happy)
  (angel "Sure, as long as it's not this lady here in charge of the choosing.")
  (elisa "Fine by me.")
  (narrate "“Why do I have to be the one in charge? This is such a pain!”")
  (hide-ui)
  (choice
   "Which game do you prefer?"
   (option "Elisa's." elisa-bridge)
   (option "Angel's." angel-bridge)
   (option "Both of these suck!" none-chosen)
   (default "Elisa's")))

(defscene day-2
  (show-ui)
  (mom "Alex! I'm heading out, are you up yet?")
  (background :background)
  (alex "Wha-")
  (narrate "I abruptly wake up as my brain tries to realize what is happening.")
  (narrate "The last thing I remember was reading something about loops and components on a blog article, I must have fallen asleep.")
  (narrate "I glance at the clock and...")
  (set-cps 0)
  (narrate "“10AM?”")
  (set-cps 30)
  (narrate "“Kurt's gonna kill me... the meeting was 2 hours ago.”")
  (narrate "I look at my cellphone. I have ten missed calls and two messages. From Kurt.")
  (narrate "I take a glance at my email client. Three unread messages. One from each member of my team.")
  (narrate "I gloomily head to the restroom to wash my face, on the way back I also grab a bowl of cereals for breakfast.") ; BACKGROUND BREAKFAST??
  (narrate "In order to properly wake my brain up, I gently slap my cheeks with both hands.")
  (narrate "“Alright, let's do this!”")
  (background :irc)
  (narrate "Upon joining the IRC channel, I find the others arguing over something. I keep reading without interrupting, they will eventually notice me.")
  (clear-sprites)
  (move-group-sprite)
  (sprite :angelblue-angry)
  (sprite :elisa-angry)
  (sprite :kurt-angry)
  (angel "I say we go with my idea. You called me here as a game designer so just listen to me.")
  (elisa "We should go with something simpler... We only have 48 hours...")
  (angel "To hell with something simple! Your idea's just too easy!")
  (kurt "Listen, Blue... Your idea is really hard, how do you even make it fit the theme?")
  (angel "Well, the theme's just stupid. And don't call me 'Blue'!")
  (elisa "My idea fits the theme...")
  (clear-sprites)
  (narrate "As I idly look at the chatlog, I open a new browser tab and head to the competition's website. I'm curious to find out what kind of theme we have to deal with.")
  (narrate "The front page of the competition is full of posts from all the participants. People enjoy sharing their progress, thoughts and ideas. There are a few posts ranting and complaining about the theme which is...") ; BACKGROUND LD
  (narrate "“\"Entire Game on One Screen\"? How is that a theme?”")
  (narrate "I am surprised at their choice of theme, it sounds more like an additional rule than a theme by itself. Intrigued, I tab back into IRC.")
  (alex "So... hi guys.")
  (sprite :angelblue-angry)
  (sprite :elisa-angry)
  (sprite :kurt-angry)
  (elisa "Hey Alex.")
  (kurt "Well, at least you decided to show up.")
  (alex "Yeah Kurt, sorry. I was up late last night reading on game development.")
  (angel "Okay Alex, listen to me. These two don't want to roll with me. I have a really good idea, but they say it's too hard. Pfft.")
  (narrate "I start typing a response, but Kurt beats me.")
  (kurt "As I said, it's not just hard. It just doesn't make sense.")
  (alex "Listen guys... I have no idea what the hell is going on. Start from the beginning please.")
  (narrate "I try to moderate the pace since I am the developer in the team: the slave that writes code and has to deal with complex overreaching ideas.")
  (alex "What do you think of the theme?")
  (angel "It's stupid")
  (narrate "Angel's tone comes across as very aggressive even through the net. I definitely wouldn't want to be in the same room as him at the moment.")
  (elisa "It sucks")
  (kurt "We have to work with what we have, though.")
  (jump-to-scene morning-meeting-pt2))

(defscene end-of-day-1
  (narrate "Having taken care of all I had to do for the day, I notice the clock is striking midnight already.")
  (narrate "“I should head to bed now.”")
  (narrate "I subconsciously open my web browser and I drop a glance at Derrit's home page.")
  (narrate "Derrit is a very popular content aggregator. People call it the 'lead page of the Internet'.")
  (narrate "I don't usually post on it, I'm more of a lurker. There can be a lot of interesting articles as long as one is able to take the time to wade through the piles of memes an cat pictures littering all the pages.")
  (narrate "I head over to the game dev subderrit, looking for introductory articles on game development.")
  (narrate "I smile, reading various blog posts and tutorials.")
  (narrate "“Maybe this isn't too bad, after all.”")
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "I slowly fall asleep in front of my computer...")
  (normal-text)
  (jump-to-scene day-2))

(defblock elisa-email
  (narrate "From the subject it looks like a generic greetings message. For an instant I consider trashing it along with the dozens of other spam messages I receive daily, but then my curiosity manages to get the best of me.")
  (narrate "I open it and prompty look for the signature in order to find out who the mysterious stranger might be.")
  (narrate "It seems to be from Elisa.")
  (narrate "“Kurt... That asshole even gave her my contact info!”")
  (narrate "I curse between my teeth as I begin reading her message, it is related to the Ludum Dare.")
  (sprite :elisa-happy)
  (elisa "Hi. Elisa here, from class. Kurt told me that you guys need an artist for a game competition. It sounds really fun!")
  (narrate "“It sure does... ...”")
  (elisa "He told me to meet tomorrow morning on IRC but he forgot to tell me how. I'm not very familiar with it since I have never used it before.")
  (elisa "He also mentioned you know a lot about computers, can you help me set this up? Can I add you on Psyke?")
  (clear-sprites)
  (narrate "Psyke is a proprietary program used to chat, with voice and cam.")
  (narrate "“Why is it always me?”")
  (background :psyke)
  (narrate "I reluctantly reply to her email with my Psyke address. Soon enough, a friendship request appears on my screen.") ; BACKGROUND PSYKE CLIENT
  (narrate "I open my client and click on the call button. As it keeps beeping I reach for my headset.")
  (sprite :elisa-happy)
  (elisa "Hello...?")
  (narrate "Elisa quickly answers the call. Through the webcam I see a girl with unkempt red hair wearing a plain brown hoodie. A few strands of hair fall in front of her face as she fumbles with the microphone.")
  (elisa "Is this thing even on?")
  (narrate "I click on my cam button and a light blinks on the screen, showing my big ugly face in full view.")
  (narrate "She notices me and blushes, stuttering a few words. I must have surprised her.")
  (no-sprite :elisa-happy)
  (sprite :elisa-blush)
  (elisa "O-oh... H-hi!")
  (alex "Hello. I'm Alex, nice to meet you. Did you install the IRC client already?")
  (narrate "I cut straight to the point, it's late and I don't really feel like doing this.")
  (elisa "I'm El- oh... the IRC client, yes. I got one from the Internet.")
  (no-sprite :elisa-blush)
  (sprite :elisa-happy)
  (alex "Good, this way it will be faster. You just have to connect to our school network...")
  (clear-backgrounds)
  (clear-sprites)
  (hide-ui)
  (narrator-text)
  (narrate "20 minutes later...")
  (normal-text)
  (sprite :elisa-happy)
  (background :background) ; BACKGROUND PSYKE
  (background :psyke)
  (show-ui)
  (elisa "So, tomorrow morning I just reconnect and the options will stay there?")
  (alex "Exactly.")
  (narrate "I massage my temples as I feel a headache brewing at the back of my head.")
  (narrate "“I'm really not everyone's personal tech support.”")
  (narrate "I copy and paste some link into the chat with Elisa.")
  (alex "If you have any more questions, the program's manual is fairly simple.")
  (elisa "No no, I think I got it.")
  (elisa "Well, thank you so much! See you tomorrow morning then. It will be fun.")
  (alex "Yeah...")
  (clear-sprites) ; REMOVE BACKGROUND PSYKE
  (no-background)
  (narrate "I hang up and disconnect from Psyke, my mind already wandering to other stuff."))

(defblock angelblue-irc
  (narrate "I reach with my cursor for the IRC app and connect to the school network.")
  (background :irc)
  (narrate "“Let's make this quick...”")
  (narrate "I look through the list of channels and users connected, searching for somebody named AngelBlue.")
  (narrate "I spot his name in a channel called 'Dolls'.")
  (narrate "“This guy is really a weirdo.”")
  (alex "Hey")
  (narrate "I send him a private IM and then wait for his reply.")
  (sprite :angelblue-normal)
  (angel "?")
  (angel "Who's this?")
  (alex "Alex here, I'm Kurt's friend.")
  (angel "Kurt? Who's that?")
  (narrate "I start tapping my fingers on my desk, my patience is running out.")
  (alex "Listen, man. Do you want to help us with Ludum Dare or not?")
  (angel "Ludum Dare? You're friend with LittleBiscuit19? Ok. I'm in the middle of a raid atm, tell me the channel and time for tomorrow.")
  (narrate "“LittleBiscuit19? Is that the nickname Kurt uses online?”")
  (narrate "I smirk at myself imagining Kurt's reaction after telling him I know.")
  (alex "Ok buddy, see you tomorrow then.")
  (narrate "I copypaste in chat the details of the meeting and close the client.")
  (no-background)
  (clear-sprites)
  (narrate "“What have I gotten into?”"))

(defscene meet-elisa-email ; BACKGROUND EMAIL CLIENT
  (show-ui)
  (narrate "I glance at the email I received.")
  (elisa-email)
  (narrate "“And now... Let's go meet that AngelBlue guy.”")
  (narrate "Even though it's late, I figure I should still check on IRC as Kurt had asked me.")
  (angelblue-irc)
  (jump-to-scene end-of-day-1))

(defscene meet-angelblue-irc ; BACKGROUND IRC CLIENT
  (show-ui)
  (angelblue-irc)
  (narrate "I am about to head to bed when I remember I have an unread email in my inbox.")
  (narrate "“I guess I can't let you stay unread, can I?”")
  (elisa-email)
  (jump-to-scene end-of-day-1))

(defscene after-flashback-yes
  (show-ui)
  (pc "BEEP")
  (background :background) ; BACKGROUND EMAIL CLIENT
  (narrate "A noise from my computer snaps me back to reality.")
  (narrate "“Curse you Kurt for dragging me into this, I don't even know how to code a videogame!”")
  (narrate "I look at the screen, there is a new email in my inbox.")
  (narrate "“It's from Kurt... finally.”")
  (narrate "I had done some investigating regarding Ludum Dare. They have a website and thousands of people participate every time.")
  (narrate "It costs nothing to sign up, no strings attached. There is no prize, just the 'fame' and 'fun' of making a game.")
  (narrate "“I don't really see the point of this but people enjoy it, apparently.”")
  (narrate "I open Kurt's email and scroll through the text. There's a bunch of stuff I already know from reading the website. I lazily skim past it.")
  (sprite :kurt-happy)
  (kurt "They will announce the theme tomorrow morning, until then we can't do any planning. We will meet on IRC after it starts for some brainstorming.")
  (narrate "IRC, or Internet Relay Chat, is a protocol used online for multiple people to chat together.")
  (kurt "I will most likely take care of the music, and you will work on the game code. We will also need somebody to do the art.")
  (kurt "I asked Elisa to help us, she's good with that stuff. Did you see her Noartdev profile? She's got some real skills, man, I tell you.")
  (narrate "Noartdev is a popular website where users share their artworks and rate each other.")
  (set-cps 70)
  (narrate "“What?!”")
  (set-cps 30)
  (narrate "Elisa is a girl from our class. She is a loner and not very social, I have never talked to her. I have no idea how Kurt even knows her.")
  (narrate "I keep scrolling through the email, there's more of it.")
  (kurt "Also, we'll need a game designer to come up with a good idea. The guy that told me about Ludum Dare said he wanted to help and he's big into games, he hangs out on our school's IRC network.")
  (kurt "Will you tell him to join us tomorrow morning? I have to go to band practice now, he goes by the name 'AngelBlue'. Thank you!")
  (clear-sprites)
  (narrate "“What the hell? AngelBlue... How old is this guy?”")
  (narrate "I let out a faint sigh. “Why did I accept to do this, again?”")
  (pc "BEEP")
  (narrate "My computer beeps again, this time it's an email from an address I don't know.")
  (narrate "I check the time on my digital clock, it's 10pm. I consider going to bed earlier than usual to be properly rested for the competition, however I should first take care of some things.")
  (hide-ui)
  (choice
   "What will you do?"
   (option "Open the email." meet-elisa-email)
   (option "Log on IRC." meet-angelblue-irc)
   (default "Open the email.")))

(defscene yes-ludum-dare
  (show-ui)
  (alex "Alright alright, but if something more fun comes up I'll just drop this stuff, okay?")
  (clear-sprites)
  (sprite :kurt-happy)
  (kurt "Awesome! Don't worry, I'll make sure such a thing won't happen.")
  (narrate "“What the hell is that even supposed to mean?”")
  (kurt "Listen... now I gotta go, I'll send you an IM later with the details. The compo starts tomorrow morning so don't oversleep!")
  (alex "... as if ...")
  (clear-sprites)
  (hide-ui)
  (clear-backgrounds)
  (narrator-text)
  (narrate "DISCLAIMER: The author is fully aware that the Ludum Dare 48H competition is for single developers.")
  (narrate "DISCLAIMER: This is another 'Ludum Dare' taking place in a parallel universe.")
  (normal-text)
  (background :background)
  (jump-to-scene after-flashback-yes))

(defscene aw-come-on-6
  (show-ui)
  (kurt "Okay listen, you're gonna get the bad end if you keep this up. So just pick the other choice.")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "FINE" yes-ludum-dare)
   (default "FINE")))
(defscene aw-come-on-5
  (show-ui)
  (kurt "Aw come on...")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-6)
   (default "Heh... why not...")))
(defscene aw-come-on-4
  (show-ui)
  (kurt "Aw come on...")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-5)
   (default "Heh... why not...")))
(defscene aw-come-on-3
  (show-ui)
  (kurt "Aw come on...")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-4)
   (default "Heh... why not...")))
(defscene aw-come-on-2
  (show-ui)
  (kurt "Aw come on...")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-3)
   (default "Heh... why not...")))
(defscene aw-come-on-1
  (show-ui)
  (kurt "Aw come on...")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-2)
   (default "Heh... why not...")))

(defscene kurt-flashback
  (show-ui)
  (sprite :kurt-happy)
  (kurt "Yo, lazy ass!")
  (alex "Hey man, s'up?")
  (narrate "Kurt and I have been friends since we were kids, he's my neighbor and our parents had known each other for years. He's what you'd call a childhood friend.")
  (kurt "You're good with computers, aren't you?")
  (narrate "“Oh boy, here we go again...”")
  (alex "No, I won't fix your damn craptop again. It's too old and it won't run those games, just drop it and buy a new one. Get real.")
  (kurt "No no, man, hear me out.")
  (kurt "Do you know what Ludum Dare is?")
  (narrate "“Ludum... dare? Sounds exotic”")
  (alex "Never heard of it, a new game?")
  (kurt "Even better!")
  (no-sprite :kurt-happy)
  (sprite :kurt-fire)
  (narrate "His eyes suddenly light up, he's on fire, this is never a good sign.")
  (kurt "It's a game competition! Do you want in?")
  (alex "I'm not good at playing games, sorry.")
  (narrate "“Computers are for working, not playing.”")
  (kurt "No, you dumb, it's a game DEV competition. Participants are given 48 hours and a theme and they have to come up with a game prototype from scratch.")
  (alex "Sounds like a waste of time.")
  (no-sprite :kurt-fire)
  (sprite :kurt-angry)
  (kurt "Don't be such a buzzkiller, you weren't planning to do anything this weekend anyway. Come on let's team up, we can make the best game ever!")
  (narrate "His enthusiam is annoying, I look around trying to find an excuse to eject myself from the conversation but he's all over my face.")
  (alex "Didn't you say yesterday that we'd be going to the fair this Saturday?")
  (kurt "Who cares about the fair, come on be real, this is a huge opportunity. It's gonna be fun!")
  (hide-ui)
  (choice
   "Will you participate?"
   (option "Heh... why not..." yes-ludum-dare)
   (option "No way, that stuff is for kids." aw-come-on-1)
   (default "Heh... why not...")))

(defscene beginning
  (set-bounds 200 200 (- 1280 300) (- 800 540))
  (narrate "“Make a game in 48 hours?”")
  (set-bounds 260 300 (- 1280 300) (- 800 540))
  (narrate "“As if... I'm not even sure I could do that, to be honest.”")
  (set-bounds 320 400 (- 1280 800) (- 800 540))
  (narrate "“I just like computers... that's all.”")
  (bgm :main-theme)
  (normal-text)
  (show-ui)
  (narrate "I'm sitting in my room, lazily looking out of a window. It's the late afternoon of a cold December Friday.")
  (narrate "Normally I would be happy with the weekend approaching. I dislike school, it's boring, overrated and all my teachers hate me. I can't wait to be out there, in the real world, doing things that matter. I'm already working with my father as a side-job, programming, why would I need school?")
  (narrate "Today, however, I am worried about what will come out of this weekend. I am certainly not looking forward to it.")
  (narrate "“Damn Kurt, how could he do that to me...”")
  (narrate "Silently, gazing at some children playing outside in the snow, I recall the events of this morning.")
  (jump-to-scene kurt-flashback))

(defscene start
  (init)
  (jump-to-scene beginning))
